# workflow which lints and checks the rust code on every push and pull request
name: Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v4

      # https://github.com/actions/setup-python
      - name: set up python
        uses: actions/setup-python@v5
        with:
          # cache: 'pip' # caching pip dependencies
          python-version: "3.13"

      # https://github.com/pre-commit/action
      - name: run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch

  trialrun:
    needs: check
    uses: "./.github/workflows/dockerimage.yml"
    with:
      container_name: ci-workflow-tester
      context_path: .tester
      push: true
    secrets: inherit
