name: docker

"on":
  workflow_call:
    inputs:
      build_args:
        description: >-
          Additional build arguments in `KEY=VALUE` format, preferrably one per
          line
        required: false
        type: string
        default: ""
      container_name:
        description: >-
          The base name of the docker container; e.g. just the "xyz" part of
          "edence/xyz:latest"
        required: true
        type: string
      context_path:
        description: >-
          The path (relative within the repo) of the directory that contains
          the Dockerfile
        required: false
        type: string
        default: .
      dockerhub_org:
        description: >-
          The Docker Hub organization name or username where the image should
          be uploaded; e.g. just the "edence" part of "edence/xyz:latest";
          leave blank to skip the normal Docker Hub tag
        required: false
        type: string
        default: ${{ github.repository_owner == 'edencehealth' && 'edence' || github.repository_owner }}
      github_org:
        description: >-
          The GitHub organization name or username where the image should be
          uploaded; e.g. just the "edencehealth" part of
          "edencehealth/xyz:latest"; leave blank to skip the normal GitHub tag
        required: false
        type: string
        default: ${{ github.repository_owner }}
      lfs:
        description: >-
          whether to include Git Large File Storage files when checking-out the
          code repo
        required: false
        type: boolean
        default: false
      platforms:
        description: >-
          Quoted JSON string specifying a list of target platform(s) to use
          when building the image
        required: false
        type: string
        default: |-
          ["linux/amd64","linux/arm64"]
      push:
        description: >-
          Whether to push the image to the container registries (building
          without pushing may be useful as a PR check)
        required: false
        type: boolean
        default: ${{ github.event_name != 'pull_request' }}
      push_readme:
        description: >-
          Path of the README file to push to Docker Hub. This runs only if the
          dockerhub_org and container_name inputs are non-empty. The Docker Hub
          repo's long_description will be set to the contents of the given
          readme file. The Docker Hub short description will be set from the
          GitHub repo's description. This only runs if the "latest" image tag
          would be updated.
          (example value: "./README.md")
        required: false
        type: string
        default: ""
      registry:
        description: >-
          Server address of an additional Docker registry to log into
        required: false
        type: string
        default: ""
      registry_paths:
        description: >-
          Additional registry paths, preferrably one per line (for example
          "docker.io/bitnami/redis" without ":latest")
        required: false
        type: string
        default: ""
      runs_on:
        description: >-
          Quoted JSON string specifying a list of Workflow Runner machine
          types/labels to run the job on (note the variable name contains an
          underscore not a dash) - the value is processed using `fromJson`;
          example self-hosted runner value "['self-hosted', 'linux']"
        required: false
        type: string
        default: |-
          ["ubuntu-latest", "ubuntu-latest-arm"]
    outputs:
      tags:
        description: >-
          The docker tags that were ultimately generated
        value: ${{ jobs.build.outputs.tags }}
    secrets:
      dockerhub_token:
        description: >-
          The Docker Hub personal access token to use when uploading the image
        required: false
      dockerhub_username:
        description: >-
          The Docker Hub username to use when uploading the image
        required: false
      registry_password:
        description: >-
          Password or token used to log into the additional registry
        required: false
      registry_username:
        description: >-
          Username or Key ID used to log into the registry
        required: false

jobs:
  build:
    # https://docs.github.com/en/actions/examples/using-scripts-to-test-your-code-on-a-runner#example-workflow
    # https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        runner: ${{ fromJSON(inputs.runs_on) }}
    outputs:
      tags: |-
        ${{ steps.meta.outputs.tags }}
      digest: ${{ steps.build.outputs.digest }}
      namelist: ${{ steps.convert.outputs.namelist }}
    env:
      DOCKER_LOGIN: ${{ secrets.dockerhub_username != '' && secrets.dockerhub_token != '' }}
      REGISTRY_LOGIN: ${{ secrets.registry_username != '' && secrets.registry_password != '' }}
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          lfs: ${{ inputs.lfs }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        if: ${{ inputs.dockerhub_org != '' && env.DOCKER_LOGIN == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}

      # https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        if: ${{ inputs.github_org != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/login-action
      - name: Login to generic container registry
        if: ${{ inputs.registry != '' && env.REGISTRY_LOGIN == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |-
            ${{ inputs.github_org != '' && format('ghcr.io/{0}/{1}', inputs.github_org, inputs.container_name) || '' }}
            ${{ inputs.dockerhub_org != '' && env.DOCKER_LOGIN == 'true' && format('{0}/{1}', inputs.dockerhub_org, inputs.container_name) || '' }}
            ${{ inputs.registry_paths != '' && env.REGISTRY_LOGIN == 'true' && inputs.registry_paths || '' }}
          tags: |-
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=pr
            type=sha

      - name: Convert Values
        id: convert
        shell: python
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          RUNNER: ${{ matrix.runner }}
        run: |
          #!/usr/bin/env python3
          import os
          import shlex

          def gh_output(name: str, value: str) -> None:
              """write a value to the github workflow step output"""
              output_file = os.environ["GITHUB_OUTPUT"]
              with open(output_file, "at", encoding="utf-8") as out:
                  out.write(f"{name}={value}\n")

          tags = os.environ["TAGS"]
          runner = os.environ["RUNNER"]

          # with tags like this:
          # "tags": [
          #   "ghcr.io/edencehealth/ohdsi-ares:pr-6",
          #   "ghcr.io/edencehealth/ohdsi-ares:sha-16b6dae",
          #   "edence/ohdsi-ares:pr-6",
          #   "edence/ohdsi-ares:sha-16b6dae"
          # ]
          # the namelist is "edence/ohdsi-ares,ghcr.io/edencehealth/ohdsi-ares"

          base_tag_set = {tag.split(":", 1)[0] for tag in tags.splitlines()}
          namelist = shlex.quote(",".join(sorted(base_tag_set))) # edence/ohdsi-ares,ghcr.io/edencehealth/ohdsi-ares

          gh_output("namelist", namelist) # edence/ohdsi-ares,ghcr.io/edencehealth/ohdsi-ares
          gh_output("quoted_namelist", f'"{namelist}"') # once again, with FEELING!
          gh_output("platform", "linux/arm64" if "arm" in runner else "linux/amd64")
          gh_output("platform_pair", runner.replace('/', '-')) # e.g. "linux-amd64"

      # https://github.com/docker/build-push-action
      - name: Build and push-by-digest
        id: build
        uses: docker/build-push-action@v6
        with:
          build-args: |-
            COMMIT_SHA=${{ github.sha }}
            GITHUB_TAG=${{ github.ref_name }}
            GIT_COMMIT=${{ github.sha }}
            GIT_TAG=${{ github.ref_name }}
            ${{ inputs.build_args != '' && inputs.build_args || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ inputs.context_path }}
          labels: |-
            ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ steps.convert.outputs.namelist }},push-by-digest=true,name-canonical=true,push=${{ inputs.push }}
          platforms: ${{ steps.convert.outputs.platform }}

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      # https://github.com/actions/upload-artifact
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ steps.convert.outputs.platform_pair }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1


  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      DOCKER_LOGIN: ${{ secrets.dockerhub_username != '' && secrets.dockerhub_token != '' }}
      REGISTRY_LOGIN: ${{ secrets.registry_username != '' && secrets.registry_password != '' }}
    steps:
      # https://github.com/actions/download-artifact
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/metadata-action
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |-
            ${{ inputs.github_org != '' && format('ghcr.io/{0}/{1}', inputs.github_org, inputs.container_name) || '' }}
            ${{ inputs.dockerhub_org != '' && format('{0}/{1}', inputs.dockerhub_org, inputs.container_name) || '' }}
            ${{ inputs.registry_paths != '' && inputs.registry_paths || '' }}
          tags: |-
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=pr
            type=sha

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        if: ${{ inputs.dockerhub_org != '' && env.DOCKER_LOGIN == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}

      # https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        if: ${{ inputs.github_org != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/login-action
      - name: Login to generic container registry
        if: ${{ inputs.registry != '' && env.REGISTRY_LOGIN == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Create and push manifest list
        id: merge-push
        shell: python
        env:
          NAMELIST: ${{ needs.build.outputs.namelist }}
        run: |
          #!/usr/bin/env python3
          import os
          import json
          import subprocess

          def gh_output(name: str, value: str) -> None:
              """write a value to the github workflow step output"""
              output_file = os.environ["GITHUB_OUTPUT"]
              with open(output_file, "at", encoding="utf-8") as out:
                  out.write(f"{name}={value}\n")

          metadata = json.loads(os.environ["DOCKER_METADATA_OUTPUT_JSON"])
          names = os.environ["NAMELIST"].split(",")

          for name in names:
            create_cmd = "docker buildx imagetools create".split()
            for tag in metadata['tags']:
              create_cmd.extend(["--tag", tag])
            for annotation in metadata['annotations']:
              create_cmd.extend(["--annotation", annotation])
            for digest in os.listdir("/tmp/digests"):
              create_cmd.append(f"{name}@sha256:{digest}")

            subprocess.check_call(create_cmd)

            # get the first tag that corresponds with name (e.g. tag "edence/ohdsi-ares:pr-6" corresponds with name "edence/ohdsi-ares")
            first_tag = next(tag for tag in metadata['tags'] if tag.startswith(name))

            inspect_cmd = "docker buildx imagetools inspect".split()
            inspect_cmd.append(first_tag)
            subprocess.check_call(inspect_cmd)

  readme:
    if: >-
      github.ref == format('refs/heads/{0}', github.event.repository.default_branch) &&
      inputs.push_readme != '' &&
      inputs.dockerhub_org != '' &&
      inputs.container_name != ''
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.push_readme }}
          sparse-checkout-cone-mode: false

      # https://github.com/peter-evans/dockerhub-description
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
          repository: ${{ format('{0}/{1}', inputs.dockerhub_org, inputs.container_name) }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ${{ inputs.push_readme }}
